import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Player</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Player</h1>
        <br />

        <div>This page needs to be dynamic</div>
        <ul>
          <li>Clean your room</li>
          <li>Read a book</li>
          <li>Wash the dishes</li>
          <li>Walk with the dog</li>
          <li>Be nice to mam</li>
          <li>...</li>
        </ul>
        <button className={styles.button}>Great you finished it!</button>
        <button className={styles.button}>
          <Link href="/playeroverview">Go find the overview</Link>
        </button>
        <button className={styles.button}>Logg out!</button>
      </main>
    </div>
  );
}
