import Head from 'next/head';
import Link from 'next/link';
import { useState } from 'react';
import styles from '../styles/Home.module.css';
export default function Home() {
  const [test, setTest] = useState(false);
  function testToggle() {
    const newTest = !test;
    setTest(newTest);
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Player</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Player</h1>
        <br />

        <div>This page needs to be dynamic</div>
        <ul>
          <li>Clean your room</li>
          <li>Read a book</li>
          <li>Wash the dishes</li>
          <li>Walk with the dog</li>
          <li>Be nice to mam</li>
          <li>...</li>
        </ul>
        <button className={styles.button} onClick={() => testToggle()}>
          Test : {!test ? 'Great you finished it!' : 'Keep trying'}
        </button>
        <button className={styles.button}>
          <Link href="/playeroverview">Go find the overview</Link>
        </button>
        <button className={styles.button}>
          <Link href="/creattask">Creat a new task!</Link>
        </button>
        <button className={styles.button}>
          <Link href="./">Logg Out!</Link>
        </button>
      </main>
    </div>
  );
}
