import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Player Overview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Player Overview</h1>

        <div>This page needs to be dynamic</div>
        <img src="/medium.png" alt="medium happy" width="300" height="350" />
        <button className={styles.button}>
          <Link href="/player">what is up for you?</Link>
        </button>
      </main>
    </div>
  );
}
